# Generated by Django 4.2.3 on 2023-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image3',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
