# Generated by Django 3.2.10 on 2023-08-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_Room', '0003_alter_room_image1_alter_room_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Capacity',
            field=models.IntegerField(default=1),
        ),
    ]
