# Generated by Django 3.2.10 on 2023-08-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_Room', '0004_room_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Capacity',
            new_name='capacity',
        ),
    ]
