# Generated by Django 4.2.3 on 2023-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
