# Generated by Django 4.2.3 on 2023-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="Is_employee",
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
