# Generated by Django 4.2.3 on 2023-07-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_is_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="Is_employee",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
