# Generated by Django 4.2.3 on 2023-07-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_is_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_name",
        ),
    ]
